services:
  etherapistdb:
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "1433:1433"
    hostname: etherapist
    container_name: etherapistDB
    environment:
      - MSSQL_SA_PASSWORD=ExamplePassword123
      - ACCEPT_EULA=Y